service: data-collector

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-south-2
  stage: dev
  profile: HarketDev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:eu-south-2:*:*"

functions:
  collectDataFunction:
    handler: src/lambdas/collectData.handler
  processDataFunction:
    handler: src/lambdas/processData.handler
    events:
      - s3:
          bucket: datacollectorbucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: "uploads/"
            - suffix: ".txt"

resources:
  Resources:
    DataCollectorBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "datacollectorbucket"

    DataCollectorTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "DataCollectorTable${self:provider.stage}"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        
plugins:
  - serverless-offline
