service: data-processing

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-south-2
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "dynamodb:*"
      Resource: "*"

functions:
  processDataFunction:
    handler: src/processData.handler
    events:
      - s3:
          bucket: dataprocessingbucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: "uploads/"
            - suffix: ".txt"
